---
  - hosts: web
    remote_user: ubuntu
    become: yes
    ignore_errors: yes
    tasks:
           - name: create a user
             user: 
                      name: funsho
                      comment: funsho lasisi
           - name: create a directory
             file: 
                      path: /home/ubuntu/ansiblewashere
                      state: directory
                      mode: '0755'
           - name: create a file
             file: 
                      path: /home/ubuntu/ansiblewashere/readme.md
                      state: touch
           - name: Write into readme.md file
             shell: echo "
                    This is my First editing with ansible
                    " >> /home/ubuntu/ansiblewashere/readme.md           
           - name: install Apache2
             apt: 
                      name: apache2
                      state: present
           - name: Start apache2
             service:
                      name: apache2
                      state: started          
           - name: Write into a file
             shell: echo "
                    Hello world
                  " > /var/www/html/index.html 
